### ISSUE TITLE
TIme slot doesn't scale properly for minutes

### ISSUE THREAD

**Issue by ashrufsyed** [pklaus/timetable#2]
The minutes of the time slot provided in the tex file will not scale the row length with 60 minutes as reference. Instead it seems to be considering 100 min = 1 hr.
This can be clearly seen in the timetable output where the time slot for _Data Networks Lecture_ from _2:30PM to 4PM_ on _Monday_ in the sample tex file you provided did not start from half width of 2PM to 3PM box, instead it began approx at one third of the row length which implies it is scaling the hour as 100min instead of 60min!

**Comment by pklaus** [comment]
The data networks lecture is supposed to go from 14:15 to 16:00 (see example.tex). So it seems like the behaviour is correct. Is this why you closed the issue?

**Comment by ashrufsyed** [comment]
Hey Philipp,

Sorry to bother you on this! Yeah, I had the issue because I chose a
timeslot of 20min instead of 15min, and slotting did not scale properly.
But later I realized it was a mistake on my side. Now I have slotted it in
a better way.

Also is it possible to maintain the same row length with smaller time
slots, as you might know, that decreasing the timeslots for precision in
the slotting will increase the row length, and the content overflows!

On Wed, May 18, 2016 at 3:37 PM, Philipp Klaus notifications@github.com
wrote:

> The data networks lecture is supposed to go from 14:15 to 16:00 (see
> example.tex). So it seems like the behaviour is correct. Is this why you
> closed the issue?
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/pklaus/timetable/issues/2#issuecomment-219982884

## 

Thanks & regards,
Syed Ashruf || AE13D030,
Doctoral Student, Computational Combustion Lab,
Department of Aerospace Engineering,
IIT Madras\* ||\* +919791095572
